### ISSUE TITLE
New patches available in Debian SID for kernel 6.1

### ISSUE THREAD

**Issue by pigeonskiller** [archlinux-jerry/nvidia-340xx#2]
Just for info Debian SID already has drivers patched for kernel 6.1 called nvidia-legacy-340xx-driver.

Please check it out here:
https://metadata.ftp-master.debian.org/changelogs//non-free/n/nvidia-graphics-drivers-legacy-340xx/nvidia-graphics-drivers-legacy-340xx_340.108-17_changelog

**Comment by isjerryxiao** [comment]
I was aware of the debian patch. The plan is to switch to the debian patches entirely when kernel 6.2 releases if it breaks the driver again. In terms of 6.1, I don't see the necessity of a patch as it works just fine with the current patches. As a result, the AUR out of date flag is cleared.

**Comment by expatjedi** [comment]
Jerry, will be there any patch for the package nvidia-340xx-lts? Current nvidia drivers does not work with kernel 6.1.12-1-lts

**Comment by pigeonskiller** [comment]
@ expatjedi

Hi, follow this https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-340/+bug/1916640/comments/28
to solve your problem.
I'm on Kubuntu but it works flawlessly with latest drivers.

**Comment by expatjedi** [comment]
@pigeonskiller Thank you but I use arch linux.

**Comment by pigeonskiller** [comment]
@ expatjed

Try this: https://github.com/MeowIce/nvidia-legacy
